Neos:
  Neos:
    nodeTypes:
      groups:
        widget:
          position: 50
          label: 'Widgets'
    fusion:
      autoInclude:
        BetterEmbed.NeosEmbed: true
    userInterface:
      translation:
        autoInclude:
          BetterEmbed.NeosEmbed:
            - 'Main'
            - 'NodeTypes/*'
